services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "4318:4318" # API
    restart: unless-stopped

  postgres:
    image: postgres:latest
    volumes:
    - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: items
    restart: unless-stopped

volumes:
  postgres_data:
