apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: redisAddr
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: natsURL
