apiVersion: apps.henkebyte.dev/v1alpha1
kind: Widget
metadata:
  labels:
    app.kubernetes.io/name: 03-operator
    app.kubernetes.io/managed-by: kustomize
  name: widget-sample
spec:
  message: "hello from my widget"
